journal_title:
  url: https://{title}-tamu.tdl.org/{title}
  token: "api-key"
  oai_endpoint: https://{title}-tamu.tdl.org/{title}/oai
  output_directory: "output"
  title: "Journal Title"
  default_thumbnail: "https:://{default}/{thumbnail}.{ext}"
  date: "2008-2016"
  description: "Description"
  subjects:
    - Motion pictures -- History
    - Motion pictures
    - Motion pictures, Mexican
    - Motion pictures, Spanish
  alternative: ""